name: Automated Data Preprocessing

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    # 1. Mengambil kode dari repositori GitHub ke server virtual
    - name: Checkout repository code
      uses: actions/checkout@v3

    # 2. Menyiapkan lingkungan Python versi 3.12
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # 3. Menginstal library yang dibutuhkan oleh skrip otomatisasi
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy scikit-learn

    # 4. Mengeksekusi skrip otomatisasi otomatis
    - name: Run preprocessing script
      run: |
        python preprocessing/automate_Titi_Alfiana.py

    # 5. Menyimpan kembali data yang sudah bersih (data_clean.csv) ke dalam GitHub repositori
    - name: Commit and push processed data
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add preprocessing/diabetes_preprocessing/data_clean.csv
        git diff --quiet && git diff --staged --quiet || (git commit -m "Automated data preprocessing updates" && git push)